
NIFTY_50_TICKERS = [
    'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'HINDUNILVR.NS',
    'ICICIBANK.NS', 'ITC.NS', 'SBIN.NS', 'BHARTIARTL.NS', 'LICI.NS',
    'KOTAKBANK.NS', 'LT.NS', 'AXISBANK.NS', 'HCLTECH.NS', 'ASIANPAINT.NS',
    'MARUTI.NS', 'SUNPHARMA.NS', 'TITAN.NS', 'BAJFINANCE.NS', 'ULTRACEMCO.NS',
    'ONGC.NS', 'NTPC.NS', 'WIPRO.NS', 'POWERGRID.NS', 'M&M.NS',
    'JSWSTEEL.NS', 'TATASTEEL.NS', 'LTIM.NS', 'ADANIENT.NS', 'ADANIPORTS.NS',
    'COALINDIA.NS', 'SIEMENS.NS', 'BAJAJFINSV.NS', 'TATAMOTORS.NS', 'PIDILITIND.NS',
    'GRASIM.NS', 'SBILIFE.NS', 'TECHM.NS', 'BRITANNIA.NS', 'INDUSINDBK.NS',
    'GODREJCP.NS', 'HINDALCO.NS', 'DIVISLAB.NS', 'EICHERMOT.NS', 'DRREDDY.NS',
    'BPCL.NS', 'CIPLA.NS', 'HEROMOTOCO.NS', 'TATACONSUM.NS', 'APOLLOHOSP.NS'
]
